/**
 * seedReservations.js - Script pour créer des réservations de test
 * Usage: node scripts/seedReservations.js
 */

const mongoose = require("mongoose");
const Reservation = require("../models/Reservation");
require("dotenv").config();

const reservations = [
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "69449f7e4a1487a5c9b0b9d6",
		orderIds: [],
		status: "en attente",
		clientName: "Martin Dupont",
		phone: "0612345678",
		nbPersonnes: 2,
		reservationDate: new Date("2026-01-10T19:00:00.000Z"),
		reservationTime: "19:00",
		reservationSource: "Sur place",
		allergies: "Gluten",
		restrictions: "",
		notes: "Préfère table près de la fenêtre",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Autre",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "69449f7e4a1487a5c9b0b9d6",
		orderIds: [],
		status: "en attente",
		clientName: "Sophie Martin",
		phone: "0698765432",
		nbPersonnes: 3,
		reservationDate: new Date("2026-01-10T19:30:00.000Z"),
		reservationTime: "19:30",
		reservationSource: "À distance",
		allergies: "Lactose",
		restrictions: "Végétarien",
		notes: "Anniversaire de mariage",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Carte",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "686af53bbb4cba684ff3b732",
		orderIds: [],
		status: "en attente",
		clientName: "Thomas Bernard",
		phone: "0654321987",
		nbPersonnes: 4,
		reservationDate: new Date("2026-01-10T20:00:00.000Z"),
		reservationTime: "20:00",
		reservationSource: "Sur place",
		allergies: "Arachides",
		restrictions: "",
		notes: "Groupe d'amis",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Autre",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "69449f7e4a1487a5c9b0b9d6",
		orderIds: [],
		status: "en attente",
		clientName: "Julie Petit",
		phone: "0677889900",
		nbPersonnes: 2,
		reservationDate: new Date("2026-01-10T20:30:00.000Z"),
		reservationTime: "20:30",
		reservationSource: "À distance",
		allergies: "Fruits de mer",
		restrictions: "",
		notes: "",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Espèces",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "686af53bbb4cba684ff3b732",
		orderIds: [],
		status: "en attente",
		clientName: "Michel Durand",
		phone: "0611223344",
		nbPersonnes: 3,
		reservationDate: new Date("2026-01-10T21:00:00.000Z"),
		reservationTime: "21:00",
		reservationSource: "Sur place",
		allergies: "",
		restrictions: "Sans sel",
		notes: "Dîner d'affaires",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Carte",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "69449f7e4a1487a5c9b0b9d6",
		orderIds: [],
		status: "en attente",
		clientName: "Claire Moreau",
		phone: "0699887766",
		nbPersonnes: 4,
		reservationDate: new Date("2026-01-10T19:15:00.000Z"),
		reservationTime: "19:15",
		reservationSource: "Sur place",
		allergies: "Œufs",
		restrictions: "Végan",
		notes: "Table à l'extérieur si possible",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Autre",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "686af53bbb4cba684ff3b732",
		orderIds: [],
		status: "en attente",
		clientName: "Pierre Laurent",
		phone: "0622334455",
		nbPersonnes: 2,
		reservationDate: new Date("2026-01-10T19:45:00.000Z"),
		reservationTime: "19:45",
		reservationSource: "À distance",
		allergies: "Soja",
		restrictions: "",
		notes: "Rendez-vous galant",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Carte",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "69449f7e4a1487a5c9b0b9d6",
		orderIds: [],
		status: "en attente",
		clientName: "Anna Kowalski",
		phone: "0633445566",
		nbPersonnes: 3,
		reservationDate: new Date("2026-01-10T20:15:00.000Z"),
		reservationTime: "20:15",
		reservationSource: "Sur place",
		allergies: "Poisson",
		restrictions: "Sans gluten",
		notes: "Touristes polonais",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Espèces",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "686af53bbb4cba684ff3b732",
		orderIds: [],
		status: "en attente",
		clientName: "Robert Chen",
		phone: "0644556677",
		nbPersonnes: 4,
		reservationDate: new Date("2026-01-10T20:45:00.000Z"),
		reservationTime: "20:45",
		reservationSource: "À distance",
		allergies: "Moutarde",
		restrictions: "",
		notes: "Famille avec enfants",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Autre",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "69449f7e4a1487a5c9b0b9d6",
		orderIds: [],
		status: "en attente",
		clientName: "Émilie Rousseau",
		phone: "0655667788",
		nbPersonnes: 2,
		reservationDate: new Date("2026-01-10T21:15:00.000Z"),
		reservationTime: "21:15",
		reservationSource: "Sur place",
		allergies: "Sésame",
		restrictions: "Halal",
		notes: "Dernière réservation de la soirée",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Carte",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	// Réservations pour le 11 janvier
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "686af53bbb4cba684ff3b732",
		orderIds: [],
		status: "en attente",
		clientName: "David Schmidt",
		phone: "0666778899",
		nbPersonnes: 3,
		reservationDate: new Date("2026-01-11T19:00:00.000Z"),
		reservationTime: "19:00",
		reservationSource: "À distance",
		allergies: "Noix",
		restrictions: "",
		notes: "Client allemand",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Carte",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "69449f7e4a1487a5c9b0b9d6",
		orderIds: [],
		status: "en attente",
		clientName: "Sarah Johnson",
		phone: "0677889901",
		nbPersonnes: 4,
		reservationDate: new Date("2026-01-11T19:30:00.000Z"),
		reservationTime: "19:30",
		reservationSource: "Sur place",
		allergies: "Céleri",
		restrictions: "Cacher",
		notes: "Touriste américaine",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Autre",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "686af53bbb4cba684ff3b732",
		orderIds: [],
		status: "en attente",
		clientName: "Kevin Muller",
		phone: "0688990011",
		nbPersonnes: 2,
		reservationDate: new Date("2026-01-11T20:00:00.000Z"),
		reservationTime: "20:00",
		reservationSource: "Sur place",
		allergies: "Mollusques",
		restrictions: "",
		notes: "",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Espèces",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "69449f7e4a1487a5c9b0b9d6",
		orderIds: [],
		status: "en attente",
		clientName: "Laura Silva",
		phone: "0699001122",
		nbPersonnes: 3,
		reservationDate: new Date("2026-01-11T20:30:00.000Z"),
		reservationTime: "20:30",
		reservationSource: "À distance",
		allergies: "Lupin",
		restrictions: "Végétalien",
		notes: "Portugaise - parle français",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Carte",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "686af53bbb4cba684ff3b732",
		orderIds: [],
		status: "en attente",
		clientName: "Marc Dubois",
		phone: "0611223345",
		nbPersonnes: 4,
		reservationDate: new Date("2026-01-11T21:00:00.000Z"),
		reservationTime: "21:00",
		reservationSource: "Sur place",
		allergies: "",
		restrictions: "Sans sucre ajouté",
		notes: "Réunion de famille",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Autre",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "69449f7e4a1487a5c9b0b9d6",
		orderIds: [],
		status: "en attente",
		clientName: "Isabelle Leroy",
		phone: "0622334456",
		nbPersonnes: 2,
		reservationDate: new Date("2026-01-11T19:15:00.000Z"),
		reservationTime: "19:15",
		reservationSource: "Sur place",
		allergies: "Crustacés",
		restrictions: "",
		notes: "Table isolée souhaitée",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Espèces",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "686af53bbb4cba684ff3b732",
		orderIds: [],
		status: "en attente",
		clientName: "Antoine Girard",
		phone: "0633445567",
		nbPersonnes: 3,
		reservationDate: new Date("2026-01-11T19:45:00.000Z"),
		reservationTime: "19:45",
		reservationSource: "À distance",
		allergies: "Sulfites",
		restrictions: "",
		notes: "Anniversaire",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Carte",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "69449f7e4a1487a5c9b0b9d6",
		orderIds: [],
		status: "en attente",
		clientName: "Caroline Mercier",
		phone: "0644556678",
		nbPersonnes: 4,
		reservationDate: new Date("2026-01-11T20:15:00.000Z"),
		reservationTime: "20:15",
		reservationSource: "Sur place",
		allergies: "Moutarde",
		restrictions: "Sans lactose",
		notes: "4 personnes dont 2 enfants",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Autre",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "686af53bbb4cba684ff3b732",
		orderIds: [],
		status: "en attente",
		clientName: "Nicolas Fontaine",
		phone: "0655667789",
		nbPersonnes: 2,
		reservationDate: new Date("2026-01-11T20:45:00.000Z"),
		reservationTime: "20:45",
		reservationSource: "À distance",
		allergies: "Arachides",
		restrictions: "",
		notes: "Première visite",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Carte",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
	{
		restaurantId: "686af511bb4cba684ff3b72e",
		serverId: "69449f7e4a1487a5c9b0b9d6",
		orderIds: [],
		status: "en attente",
		clientName: "Patricia Lambert",
		phone: "0666778890",
		nbPersonnes: 3,
		reservationDate: new Date("2026-01-11T21:15:00.000Z"),
		reservationTime: "21:15",
		reservationSource: "Sur place",
		allergies: "Fruits à coque",
		restrictions: "Sans porc",
		notes: "Dernier service accepté",
		orderSummary: "",
		dishStatus: "En attente",
		paymentMethod: "Espèces",
		totalAmount: 0,
		paidAmount: 0,
		remainingAmount: 0,
		isPresent: false,
		canceled: false,
	},
];

async function seedReservations() {
	try {
		console.log("🔗 Connexion à MongoDB...");
		await mongoose.connect(process.env.MONGO_URI);
		console.log("✅ Connecté à MongoDB");

		console.log(`📝 Insertion de ${reservations.length} réservations...`);

		const result = await Reservation.insertMany(reservations);

		console.log(`✅ ${result.length} réservations créées avec succès !`);

		console.log("\n📊 Résumé par jour:");
		const day10 = result.filter((r) =>
			r.reservationDate.toISOString().includes("2026-01-10")
		);
		const day11 = result.filter((r) =>
			r.reservationDate.toISOString().includes("2026-01-11")
		);

		console.log(`   10 janvier: ${day10.length} réservations`);
		console.log(`   11 janvier: ${day11.length} réservations`);

		console.log("\n📋 Horaires du 10 janvier:");
		day10
			.sort((a, b) => a.reservationTime.localeCompare(b.reservationTime))
			.forEach((r) => {
				console.log(
					`   ${r.reservationTime} - ${r.clientName} (${r.nbPersonnes} pers.)`
				);
			});

		console.log("\n📋 Horaires du 11 janvier:");
		day11
			.sort((a, b) => a.reservationTime.localeCompare(b.reservationTime))
			.forEach((r) => {
				console.log(
					`   ${r.reservationTime} - ${r.clientName} (${r.nbPersonnes} pers.)`
				);
			});

		console.log("\n👥 Total personnes:");
		const totalPeople = result.reduce((sum, r) => sum + r.nbPersonnes, 0);
		console.log(`   ${totalPeople} personnes au total`);

		await mongoose.connection.close();
		console.log("\n✅ Script terminé avec succès !");
	} catch (error) {
		console.error("❌ Erreur:", error);
		process.exit(1);
	}
}

// Exécuter le script
seedReservations();
